# Generated by Django 5.1.1 on 2025-04-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_address_category_remove_review_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='img_url',
        ),
        migrations.AddField(
            model_name='product_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
