# Generated by Django 4.2.20 on 2025-04-26 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.ImageField(blank=True, null=True, upload_to='face_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.user')),
            ],
        ),
    ]
