# Generated by Django 4.2.20 on 2025-05-06 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_user_face'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Khoảng cách giữa 2 đỉnh (ví dụ km)')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_in', to='main_site.address')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_out', to='main_site.address')),
            ],
        ),
    ]
